name = "dot_env"
version = "0.5.1"

description = "Load and use environment variables from files"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "dotenv" }

internal_modules = ["dot_env/internal/*"]

gleam = ">= 0.34.0"

[dependencies]
simplifile = "~> 1.5"
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
