name = "dot_env"
version = "0.2.1"

description = "Load environment variables from files"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "dotenv" }

internal_modules = [
  "dot_env/internal/*"
]

gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.32"
simplifile = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
