name = "dot_env"
version = "0.2.3"

description = "Load environment variables from files"
licences = ["Apache-2.0"]
repository = { type = "github", user = "aosasona", repo = "dotenv" }

internal_modules = [
  "dot_env/internal/*"
]

gleam = ">= 0.33.0"

[dependencies]
simplifile = "~> 1.0"
gleam_stdlib = "~> 0.34"

[dev-dependencies]
gleeunit = "~> 1.0"
