name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    env:
      HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "29.0.0"
          gleam-version: "1.17.0"
          rebar3-version: "3"
      - run: gleam publish --yes
