name: publish
on:
  release:
    types: [published]
jobs:
  publish:
    env:
      HEXPM_USER: ${{ secrets.HEXPM_USER }}
      HEXPM_PASS: ${{ secrets.HEXPM_PASS }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.34.1"
          rebar3-version: "3"
      - run: gleam publish --yes
